### ISSUE TITLE
problem with 3mo/pdf

### ISSUE THREAD

**Issue by TimotheDavid** [3mo-esolutions/web-components#84]
hello 

first really thanks for this open source package of web component , I use the @3mo/pdf for my apps and it's work realy well

nowaday ... I try to install id today in a new projet and it tell me than it need @3mo/del from npm 

can you fix it ? or can I help you to fix it ? 

thanks a lot !

**Comment by avorobiov-artelogic** [comment]
@TimotheDavid, do not use an unstable version. The bug happens due to `DialogPdf`, a part of `@3mo/pdf@^0.1.7-preview.1/2`. Just use `@3mo/pdf@0.1.6`.
